services:

  backend:
    build: ./AI-Assistant-backend
    container_name: ai-assistant-backend
    env_file:
    - ./AI-Assistant-backend/.env
    ports:
      - "8000:8000"

  frontend:
    build: ./AI-Assistant-frontend
    container_name: ai-assistant-frontend
    env_file:
    - ./AI-Assistant-frontend/.env
    ports:
      - "5173:80"
    depends_on:
      - backend