name: Deploy AI-Assistant to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      BACKEND_REPO: ${{ secrets.ECR_BACKEND_REPO }}
      FRONTEND_REPO: ${{ secrets.ECR_FRONTEND_REPO }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to ECR (backend)
      run: |
        aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
        docker login --username AWS --password-stdin ${{ env.BACKEND_REPO }}

    - name: Login to ECR (frontend)
      run: |
        aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
        docker login --username AWS --password-stdin ${{ env.FRONTEND_REPO }}

    - name: Build backend image
      run: |
        docker build -t backend ./AI-Assistant-backend
        docker tag backend:latest $BACKEND_REPO:latest
        docker push $BACKEND_REPO:latest

    - name: Build frontend image
      run: |
        docker build \
          --build-arg VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }} \
          --build-arg VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }} \
          --build-arg VITE_UPLOADS_BASE_URL=${{ secrets.VITE_UPLOADS_BASE_URL }} \
          -t frontend ./AI-Assistant-frontend

        docker tag frontend:latest $FRONTEND_REPO:latest
        docker push $FRONTEND_REPO:latest

    - name: Deploy backend to ECS
      run: |
        aws ecs update-service \
          --cluster vibrant-rabbit-py1eqp \
          --service ai-assistant-backend-task-service-owwbgu4b \
          --force-new-deployment

    - name: Deploy frontend to ECS
      run: |
        aws ecs update-service \
          --cluster vibrant-rabbit-py1eqp \
          --service ai-assistant-frontend-task-service-63gyo9ee \
          --force-new-deployment