apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi-container
          image: ai-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000

          envFrom:
            - secretRef:
                name: ai-backend-secret
            - configMapRef:
                name: ai-backend-config